# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'
networks:
  saritasa:
services:
  sql-server:
    container_name: app-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 8002:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Hung_9at1
    networks:
      - saritasa
  saritasa:
    image: saritasa
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8001:8000
    depends_on:
      - sql-server
    environment:
      - DB_HOST=app-db
      - DB_Name=Saritasa
      - DB_SA_PASSWORD=Hung_9at1
    networks:
      - saritasa
